---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos8
    image: pycontribs/centos:8
    pre_build_image: true
    command: /sbin/init
    privileged: True
  - name: ubuntu2004
    image: pycontribs/ubuntu:latest
    pre_build_image: true
    privileged: True
provisioner:
  name: ansible
verifier:
  name: ansible
