- name: Download Kibana rpm package
  tags:
    - kibana
  delegate_to: localhost
  run_once: true
  ansible.builtin.get_url:
    url: "{{ kbn_package_url }}"
    dest: "{{ playbook_dir }}/files/{{ kbn_package_name }}"
    mode: 0755
    timeout: 60
    validate_certs: false
  register: get_kibana
  until: get_kibana is succeeded
