namespace: develtime

name: services

version: 0.0.1

readme: ../README.md

authors:
  - Develtime <smirnov.v.vadim@icloud.com>

description: Develtime ansible collections

license:
  - MIT

license_file: ""

tags: []

dependencies: { "community.general": ">=3.8.0" }

repository: https://github.com/develtime/galaxy.git

documentation: https://github.com/develtime/galaxy/blob/main/README.md

homepage: https://netology.ru

issues: https://github.com/develtime/galaxy/issues

build_ignore: []
