- name: Download Elasticsearch rpm package
  tags:
    - elastic
  delegate_to: localhost
  ansible.builtin.get_url:
    url: "{{ es_package_url }}"
    dest: "{{ playbook_dir }}/files/{{ es_package_name }}"
    mode: 0755
    timeout: 60
    validate_certs: false
  register: get_elastic
  until: get_elastic is succeeded
