- name: Import "distrib.yml"
  tags:
    - elastic
  import_tasks: distrib.yml

- name: Install Elasticsearch
  tags:
    - elastic
  become: true
  yum:
    name: "/tmp/{{ es_package_name }}"
    disable_gpg_check: true
    state: present
  notify:
    - restart elastic
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 7

- name: Install Elasticsearch
  tags:
    - elastic
  become: true
  apt:
    deb: "/tmp/{{ es_package_name }}"
    force: true
    state: present
  notify:
    - restart elastic
  when: ansible_os_family == "Debian"

- name: Configure Elasticsearch
  tags:
    - elastic
  become: true
  ansible.builtin.template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    mode: 0755
  notify:
    - restart elastic
