---
- name: Upload Elasticsearch rpm package from local storage
  tags:
    - elastic
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/files/{{ es_package_name }}"
    dest: "/tmp/{{ es_package_name }}"
    mode: 0755
  register: upload_elastic
  until: upload_elastic is succeeded
