---
kbn_version: 7.14.0
kbn_port: 5601

kbn_package_name: "{% if ansible_os_family == 'RedHat' %}kibana-{{ kbn_version }}-x86_64.rpm{% else %}kibana-{{ kbn_version }}-amd64.deb{% endif %}"
kbn_package_url: "https://artifacts.elastic.co/downloads/kibana/{{ kbn_package_name }}"

kbn_es_host_group: "elasticsearch"

# If kbn_es_host_group is not presented
kbn_es_address: 127.0.0.1

kbn_es_port: 9200
