---
- name: Include "./download.yml"
  tags:
    - logstash
  import_tasks: download.yml

- name: Include "./upload.yml"
  tags:
    - logstash
  import_tasks: upload.yml

- name: Install Logstash
  tags:
    - logstash
  become: true
  dnf:
    name: "/tmp/{{ ls_package_name }}"
    disable_gpg_check: true
    state: present

- name: Change privilege for logstash directories
  tags:
    - logstash
  become: true
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    follow: yes
    owner: "{{ ls_user }}"
    group: "{{ ls_group }}"
  with_items:
    - "{{ ls_home }}"
    - "{{ ls_log_directory }}"
    - "{{ ls_conf_directory }}"
  notify:
    - restart logstash

- name: Include "./plugins.yml"
  tags:
    - logstash
  import_tasks: plugins.yml

- name: Configure Logstash logstash.yml
  tags:
    - logstash
  become: true
  ansible.builtin.template:
    src: logstash.yml.j2
    dest: "{{ ls_conf_directory }}/logstash.yml"
    mode: 0755
  notify:
    - restart logstash

- name: Configure Logstash beats-input.conf
  tags:
    - logstash
  become: true
  ansible.builtin.template:
    src: beats-input.conf.j2
    dest: "{{ ls_conf_directory }}/conf.d/beats-input.conf"
    mode: 0755
  notify:
    - restart logstash

- name: Configure Logstash beats-input.conf
  tags:
    - logstash
  become: true
  vars:
    ls_output_addresses: "{{ groups[ls_output_host_group] | map('extract', hostvars, ['ansible_default_ipv4', 'address']) }}"
  ansible.builtin.template:
    src: elasticsearch-output.conf.j2
    dest: "{{ ls_conf_directory }}/conf.d/elasticsearch-output.conf"
    mode: 0755
  notify:
    - restart logstash
