---
- name: Get list of installed plugins
  tags:
    - logstash
  become: true
  command:
    cmd: ./logstash-plugin list
    chdir: "{{ ls_home }}/bin"
  register: logstash_plugins_list
  until: logstash_plugins_list is succeeded
  changed_when: false

- name: Install configured plugins
  tags:
    - logstash
  become: true
  command:
    cmd: "./logstash-plugin install {{ item }}"
    chdir: "{{ ls_home }}/bin"
  with_items: "{{ ls_install_plugins }}"
  when: "item not in logstash_plugins_list.stdout"
  notify:
    - restart logstash
