es_version: 7.14.0
es_port: 9200

es_package_name: "{% if ansible_os_family == 'RedHat' %}elasticsearch-{{ es_version }}-x86_64.rpm{% else %}elasticsearch-{{ es_version }}-amd64.deb{% endif %}"
es_package_url: "https://artifacts.elastic.co/downloads/elasticsearch/{{ es_package_name }}"

es_seed_hosts:
  - "{{ ansible_facts['default_ipv4']['address'] | default('0.0.0.0') }}"

es_master_nodes:
  - node-1

es_node_name: "{{ es_master_nodes[0] }}"
