---
ls_user: logstash
ls_group: logstash

ls_version: 7.14.0
ls_port: 9600
ls_beats_port: 5044

ls_package_name: "logstash-{{ ls_version }}-x86_64.rpm"
ls_package_url: "https://artifacts.elastic.co/downloads/logstash/{{ ls_package_name }}"

ls_node_name: "node-1"

ls_output_host_group: "elasticsearch"
ls_output_port: 9200

ls_install_plugins:
  - logstash-input-beats
  - logstash-filter-multiline

ls_home: "/usr/share/logstash"
ls_log_directory: "{{ ls_home }}/logs"
